# Generated by Django 5.1.4 on 2024-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AS',
            fields=[
                ('a', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
            ],
        ),
    ]
