# Generated by Django 5.1.4 on 2024-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('instuction', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AS',
        ),
    ]
